# Generated by Django 3.2.11 on 2022-01-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionid', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=100)),
                ('done', models.BooleanField()),
            ],
        ),
    ]
