# Generated by Django 3.2.11 on 2022-01-13 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='sessionid',
            new_name='user',
        ),
    ]
